# Instalação via Helm:
# helm repo add autoscaler https://kubernetes.github.io/autoscaler
# helm repo update
# helm upgrade --install cluster-autoscaler autoscaler/cluster-autoscaler \
#   -n kube-system -f values.yaml

autoDiscovery:
  clusterName: cloudlab-eks

awsRegion: us-east-1

rbac:
  serviceAccount:
    create: false
    name: cluster-autoscaler

replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 256Mi

extraArgs:
  balance-similar-node-groups: true
  skip-nodes-with-system-pods: false
  scale-down-delay-after-add: 2m
  scale-down-unneeded-time: 2m
