replicaCount: 2

image:
  repository: ""
  tag: "latest"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: "frontend"
  annotations: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

env:
  API_URL: ""

livenessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 10
  periodSeconds: 20

readinessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 10

topologySpreadConstraints:
  enabled: true

podDisruptionBudget:
  enabled: true
  minAvailable: 1
