apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudlab-app
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - app
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudlab-frontend
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - app
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
